<?php
$assertions=0;$failures=[];$assert=static function(bool $c,string $m)use(&$assertions,&$failures):void{$assertions++;if(!$c){$failures[]=$m;}};$admin=get_user_by('login','admin');wp_set_current_user($admin?$admin->ID:1);global $wpdb;
$outbox=SPF_Installer::table('outbox');$wpdb->query("DELETE FROM {$outbox} WHERE event_name LIKE 'EleventhReview.%'");
$one=SPF_Event_Bus::publish('EleventhReview.One.v1','review_probe','a',['value'=>1],1,'same-caller-key','internal');$two=SPF_Event_Bus::publish('EleventhReview.One.v1','review_probe','b',['value'=>1],1,'same-caller-key','internal');$dup=SPF_Event_Bus::publish('EleventhReview.One.v1','review_probe','a',['value'=>999],1,'same-caller-key','internal');$count=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$outbox} WHERE event_name='EleventhReview.One.v1'");$assert(true===$one&&true===$two&&true===$dup&&2===$count,'Explicit dedupe key was not safely scoped/idempotent.');
add_filter('spf_file00_authorization_claim',static function($claim,array $r){$role=in_array($r['action'],['approve_release','deploy_release','approve_amendment','purge','production_cutover'],true)?'founder':'release_operator';return['claim_version'=>'1.2.0','allowed'=>true,'user_id'=>$r['user_id'],'actor_id'=>$r['user_id'],'action'=>$r['action'],'capability'=>$r['capability'],'issued_at'=>time()-5,'expires_at'=>time()+300,'claim_id'=>wp_generate_uuid4(),'object_hash'=>$r['object_hash'],'purpose'=>$r['purpose'],'institutional_role'=>$role,'plugin'=>'file-01','contract'=>SPF_CONTRACT_VERSION,'suspended'=>false,'revoked'=>false];},50,2);
update_option(SPF_Installer::SCHEMA_OPTION,'1.0.0',false);add_filter('spf_verify_migration_backup_evidence',static function($claim,array $c){return['verified'=>true,'backup_id'=>'wrong-context-backup','restore_tested_at'=>gmdate('c'),'verifier'=>'CI negative probe','module'=>'file-99','from'=>(string)($c['from']??''),'to'=>(string)($c['to']??''),'environment'=>(string)($c['environment']??''),'expires_at'=>gmdate('c',time()+3600)];},50,2);$upgrade=SPF_Installer::maybe_upgrade();$assert(is_wp_error($upgrade)&&'spf_migration_backup_evidence_binding_invalid'===$upgrade->get_error_code(),'Wrong-context migration evidence was accepted.');update_option(SPF_Installer::SCHEMA_OPTION,SPF_SCHEMA_VERSION,false);
add_filter('spf_verify_backup_restore_evidence',static function($claim,array $c){return['verified'=>true,'backup_id'=>'negative-probe','backup_checksum'=>str_repeat('a',64),'restore_tested_at'=>gmdate('c'),'restore_environment'=>'disposable-ci','verifier'=>'CI negative probe','expires_at'=>gmdate('c',time()+3600),'operation'=>'file01_purge','plan_hash'=>str_repeat('0',64)];},50,2);$plan=SPF_Purge::plan();$purge=SPF_Purge::apply('PURGE FILE 01 GOVERNANCE DATA',['backup_id'=>'submitted'],SPF_Purge::plan_hash($plan));$assert(is_wp_error($purge)&&'spf_purge_backup_evidence_binding_invalid'===$purge->get_error_code(),'Wrong-plan purge backup evidence was accepted.');
$manifest=SPF_Registry::get_module('file-01');$manifest['canonical_entities']=['Not Canonical'];$manifest['writes']=[];$mr=SPF_Installer::with_internal_seed(static fn()=>SPF_Registry::register_manifest($manifest));$assert(is_wp_error($mr)&&'spf_invalid_manifest_entity'===$mr->get_error_code(),'Noncanonical manifest entity was silently normalized.');
if($failures){fwrite(STDERR,"Eleventh ten-round runtime smoke failed:\n- ".implode("\n- ",$failures)."\n");exit(1);}echo "Eleventh ten-round runtime assertions: {$assertions}/{$assertions} PASS\n";
